
import { Exercise } from './types';

export const PAST_SIMPLE_PRESENT_PERFECT_EXERCISES: Exercise[] = [
  // Past Simple vs Present Perfect (Existing 30)
  { id: 1, sentenceTemplate: "I ______ ({verb}) Paris last year.", verb: "visit", correctAnswer: "visited", tense: "Past Simple", keywordHint: "last year" },
  { id: 2, sentenceTemplate: "She ______ ({verb}) in London since 2015.", verb: "live", correctAnswer: "has lived", tense: "Present Perfect", keywordHint: "since 2015" },
  { id: 3, sentenceTemplate: "We ______ ({verb}) that movie already.", verb: "see", correctAnswer: "have seen", tense: "Present Perfect", keywordHint: "already" },
  { id: 4, sentenceTemplate: "He ______ ({verb}) his homework an hour ago.", verb: "finish", correctAnswer: "finished", tense: "Past Simple", keywordHint: "an hour ago" },
  { id: 5, sentenceTemplate: "They ______ ({verb}) to Asia. It's their first time going next month!", verb: "never / be", correctAnswer: "have never been", tense: "Present Perfect", keywordHint: "never (life experience)" },
  { id: 6, sentenceTemplate: "My brother ______ ({verb}) a new car yesterday.", verb: "buy", correctAnswer: "bought", tense: "Past Simple", keywordHint: "yesterday" },
  { id: 7, sentenceTemplate: "I ______ ({verb}) my keys. I can't find them anywhere!", verb: "lose", correctAnswer: "have lost", tense: "Present Perfect", keywordHint: "result in present" },
  { id: 8, sentenceTemplate: "The company ______ ({verb}) many new products in the last few years.", verb: "launch", correctAnswer: "has launched", tense: "Present Perfect", keywordHint: "in the last few years" },
  { id: 9, sentenceTemplate: "When ______ you ______ ({verb}) your best friend?", verb: "meet", correctAnswer: "did you meet", tense: "Past Simple", keywordHint: "When (specific time implied)" },
  { id: 10, sentenceTemplate: "I ______ ({verb}) this book three times so far.", verb: "read", correctAnswer: "have read", tense: "Present Perfect", keywordHint: "three times so far" },
  { id: 11, sentenceTemplate: "Shakespeare ______ ({verb}) many famous plays.", verb: "write", correctAnswer: "wrote", tense: "Past Simple", keywordHint: "Shakespeare (deceased)" },
  { id: 12, sentenceTemplate: "We ______ ({verb}) to the beach last Sunday.", verb: "go", correctAnswer: "went", tense: "Past Simple", keywordHint: "last Sunday" },
  { id: 13, sentenceTemplate: "______ you ever ______ ({verb}) sushi?", verb: "eat", correctAnswer: "Have you ever eaten", tense: "Present Perfect", keywordHint: "ever (life experience)" },
  { id: 14, sentenceTemplate: "She ______ ({verb}) her leg, so she can't play tennis today.", verb: "break", correctAnswer: "has broken", tense: "Present Perfect", keywordHint: "result in present" },
  { id: 15, sentenceTemplate: "He ______ ({verb}) for this company for ten years.", verb: "work", correctAnswer: "has worked", tense: "Present Perfect", keywordHint: "for ten years (still working)" },
  { id: 16, sentenceTemplate: "They ______ ({verb}) their house last month.", verb: "sell", correctAnswer: "sold", tense: "Past Simple", keywordHint: "last month" },
  { id: 17, sentenceTemplate: "I ______ ({verb}) him yet.", verb: "not / call", correctAnswer: "haven't called", tense: "Present Perfect", keywordHint: "yet" },
  { id: 18, sentenceTemplate: "Columbus ______ ({verb}) America in 1492.", verb: "discover", correctAnswer: "discovered", tense: "Past Simple", keywordHint: "in 1492" },
  { id: 19, sentenceTemplate: "The children ______ ({verb}) all the cookies!", verb: "eat", correctAnswer: "have eaten", tense: "Present Perfect", keywordHint: "result: no cookies left" },
  { id: 20, sentenceTemplate: "I ______ ({verb}) a strange noise a few minutes ago.", verb: "hear", correctAnswer: "heard", tense: "Past Simple", keywordHint: "a few minutes ago" },
  { id: 21, sentenceTemplate: "My parents ______ ({verb}) in this town all their lives.", verb: "live", correctAnswer: "have lived", tense: "Present Perfect", keywordHint: "all their lives (still alive)" },
  { id: 22, sentenceTemplate: "The train ______ ({verb}) just ______.", verb: "arrive", correctAnswer: "has just arrived", tense: "Present Perfect", keywordHint: "just" },
  { id: 23, sentenceTemplate: "We ______ ({verb}) a great time at the party last night.", verb: "have", correctAnswer: "had", tense: "Past Simple", keywordHint: "last night" },
  { id: 24, sentenceTemplate: "It ______ ({verb}) a lot this week.", verb: "rain", correctAnswer: "has rained", tense: "Present Perfect", keywordHint: "this week (unfinished period)" },
  { id: 25, sentenceTemplate: "He ______ ({verb}) that film when he was a child.", verb: "love", correctAnswer: "loved", tense: "Past Simple", keywordHint: "when he was a child" },
  { id: 26, sentenceTemplate: "How long ______ you ______ ({verb}) her?", verb: "know", correctAnswer: "have you known", tense: "Present Perfect", keywordHint: "How long (up to now)" },
  { id: 27, sentenceTemplate: "They ______ ({verb}) the project on time.", verb: "complete", correctAnswer: "completed", tense: "Past Simple", keywordHint: "on time (specific past event)" },
  { id: 28, sentenceTemplate: "I ______ ({verb}) my homework, so I can relax now.", verb: "do", correctAnswer: "have done", tense: "Present Perfect", keywordHint: "result in present" },
  { id: 29, sentenceTemplate: "She ______ ({verb}) her first car in 2020.", verb: "buy", correctAnswer: "bought", tense: "Past Simple", keywordHint: "in 2020" },
  { id: 30, sentenceTemplate: "We ______ ({verb}) several challenges recently.", verb: "face", correctAnswer: "have faced", tense: "Present Perfect", keywordHint: "recently" },
  // New 30 exercises for Past Simple vs Present Perfect
  { id: 31, sentenceTemplate: "They ______ ({verb}) to Canada twice so far.", verb: "travel", correctAnswer: "have travelled", tense: "Present Perfect", keywordHint: "twice so far" },
  { id: 32, sentenceTemplate: "Leonardo da Vinci ______ ({verb}) the Mona Lisa.", verb: "paint", correctAnswer: "painted", tense: "Past Simple", keywordHint: "Leonardo da Vinci (deceased)" },
  { id: 33, sentenceTemplate: "I ______ ({verb}) my glasses, I can't read the board.", verb: "forget", correctAnswer: "have forgotten", tense: "Present Perfect", keywordHint: "result in present" },
  { id: 34, sentenceTemplate: "The package I was waiting for ______ ({verb}) this morning.", verb: "arrive", correctAnswer: "arrived", tense: "Past Simple", keywordHint: "this morning (finished)" },
  { id: 35, sentenceTemplate: "______ you ______ ({verb}) your dinner yet?", verb: "finish", correctAnswer: "Have you finished", tense: "Present Perfect", keywordHint: "yet" },
  { id: 36, sentenceTemplate: "My sister ______ ({verb}) from university last summer.", verb: "graduate", correctAnswer: "graduated", tense: "Past Simple", keywordHint: "last summer" },
  { id: 37, sentenceTemplate: "We ______ ({verb}) in this house since I was born.", verb: "live", correctAnswer: "have lived", tense: "Present Perfect", keywordHint: "since I was born" },
  { id: 38, sentenceTemplate: "He ______ ({verb}) a lot of money on that old car, but it still doesn't work.", verb: "spend", correctAnswer: "has spent", tense: "Present Perfect", keywordHint: "result: still doesn't work" },
  { id: 39, sentenceTemplate: "The ancient Egyptians ______ ({verb}) the pyramids.", verb: "build", correctAnswer: "built", tense: "Past Simple", keywordHint: "ancient Egyptians" },
  { id: 40, sentenceTemplate: "I ______ ({verb}) such a beautiful sunset before.", verb: "never / see", correctAnswer: "have never seen", tense: "Present Perfect", keywordHint: "never before (life experience)" },
  { id: 41, sentenceTemplate: "She ______ ({verb}) a new phone because her old one broke.", verb: "buy", correctAnswer: "bought", tense: "Past Simple", keywordHint: "because old one broke (past reason)" },
  { id: 42, sentenceTemplate: "The team ______ ({verb}) any games this season.", verb: "not / win", correctAnswer: "hasn't won", tense: "Present Perfect", keywordHint: "this season (unfinished)" },
  { id: 43, sentenceTemplate: "I ______ ({verb}) to the new café on Main Street yesterday.", verb: "go", correctAnswer: "went", tense: "Past Simple", keywordHint: "yesterday" },
  { id: 44, sentenceTemplate: "He ______ ({verb}) as a teacher for twenty years, now he is retired.", verb: "work", correctAnswer: "worked", tense: "Past Simple", keywordHint: "for twenty years (now retired)" },
  { id: 45, sentenceTemplate: "They ______ ({verb}) the results of the competition yet.", verb: "not / announce", correctAnswer: "haven't announced", tense: "Present Perfect", keywordHint: "yet" },
  { id: 46, sentenceTemplate: "When ______ the Roman Empire ______ ({verb})?", verb: "fall", correctAnswer: "did the Roman Empire fall", tense: "Past Simple", keywordHint: "When (specific past event)" },
  { id: 47, sentenceTemplate: "We ______ ({verb}) just ______ the news, it's shocking.", verb: "hear", correctAnswer: "have just heard", tense: "Present Perfect", keywordHint: "just" },
  { id: 48, sentenceTemplate: "My grandparents ______ ({verb}) in the same village all their lives, they passed away last year.", verb: "live", correctAnswer: "lived", tense: "Past Simple", keywordHint: "all their lives (deceased)" },
  { id: 49, sentenceTemplate: "The company's profits ______ ({verb}) significantly in recent months.", verb: "increase", correctAnswer: "have increased", tense: "Present Perfect", keywordHint: "in recent months" },
  { id: 50, sentenceTemplate: "I ______ ({verb}) a wonderful holiday in Italy last summer.", verb: "have", correctAnswer: "had", tense: "Past Simple", keywordHint: "last summer" },
  { id: 51, sentenceTemplate: "______ you ever ______ ({verb}) to Australia?", verb: "be", correctAnswer: "Have you ever been", tense: "Present Perfect", keywordHint: "ever (life experience)" },
  { id: 52, sentenceTemplate: "He ______ ({verb}) his speech, and everyone applauded.", verb: "finish", correctAnswer: "finished", tense: "Past Simple", keywordHint: "and everyone applauded (sequence)" },
  { id: 53, sentenceTemplate: "I ______ ({verb}) my old school friend for ages.", verb: "not / see", correctAnswer: "haven't seen", tense: "Present Perfect", keywordHint: "for ages" },
  { id: 54, sentenceTemplate: "The city ______ ({verb}) a lot since I was last here.", verb: "change", correctAnswer: "has changed", tense: "Present Perfect", keywordHint: "since I was last here" },
  { id: 55, sentenceTemplate: "They ______ ({verb}) dinner at 8 PM last night.", verb: "eat", correctAnswer: "ate", tense: "Past Simple", keywordHint: "at 8 PM last night" },
  { id: 56, sentenceTemplate: "She ______ ({verb}) already ______ three cups of coffee this morning.", verb: "drink", correctAnswer: "has already drunk", tense: "Present Perfect", keywordHint: "already, this morning (unfinished for coffee)" },
  { id: 57, sentenceTemplate: "The author ______ ({verb}) several bestsellers in the 1990s.", verb: "write", correctAnswer: "wrote", tense: "Past Simple", keywordHint: "in the 1990s" },
  { id: 58, sentenceTemplate: "We ______ ({verb}) many difficulties, but we overcame them.", verb: "face", correctAnswer: "faced", tense: "Past Simple", keywordHint: "but we overcame them (finished period)" },
  { id: 59, sentenceTemplate: "The technology ______ ({verb}) rapidly in the past decade.", verb: "evolve", correctAnswer: "has evolved", tense: "Present Perfect", keywordHint: "in the past decade" },
  { id: 60, sentenceTemplate: "I ______ ({verb}) to that song when I was a teenager.", verb: "listen", correctAnswer: "listened", tense: "Past Simple", keywordHint: "when I was a teenager" },
];

export const MIXED_TENSES_EXERCISES: Exercise[] = [
  // Mixed Tenses (Existing 30)
  { id: 101, sentenceTemplate: "Look! The children ______ ({verb}) in the garden right now.", verb: "play", correctAnswer: "are playing", tense: "Present Continuous", keywordHint: "right now, Look!" },
  { id: 102, sentenceTemplate: "While I ______ ({verb}) dinner last night, the phone rang.", verb: "cook", correctAnswer: "was cooking", tense: "Past Continuous", keywordHint: "While... last night" },
  { id: 103, sentenceTemplate: "I think it ______ ({verb}) tomorrow.", verb: "rain", correctAnswer: "will rain", tense: "Future Simple (will)", keywordHint: "tomorrow, I think" },
  { id: 104, sentenceTemplate: "By the time we arrived, the film ______ ({verb}).", verb: "already / start", correctAnswer: "had already started", tense: "Past Perfect", keywordHint: "By the time, already" },
  { id: 105, sentenceTemplate: "She ______ ({verb}) English for five years, and she's still learning.", verb: "study", correctAnswer: "has been studying", tense: "Present Perfect Continuous", keywordHint: "for five years, still learning" },
  { id: 106, sentenceTemplate: "He promised he ______ ({verb}) us with the project.", verb: "help", correctAnswer: "would help", tense: "Future in the Past", keywordHint: "promised" },
  { id: 107, sentenceTemplate: "Don't call me at 8 PM because I ______ ({verb}) dinner then.", verb: "have", correctAnswer: "will be having", tense: "Future Continuous", keywordHint: "at 8 PM ... then" },
  { id: 108, sentenceTemplate: "Water ______ ({verb}) at 100 degrees Celsius.", verb: "boil", correctAnswer: "boils", tense: "Present Simple", keywordHint: "general truth" },
  { id: 109, sentenceTemplate: "They ______ ({verb}) to the cinema every Friday.", verb: "go", correctAnswer: "go", tense: "Present Simple", keywordHint: "every Friday (habit)" },
  { id: 110, sentenceTemplate: "I ______ ({verb}) my wallet. Can you help me look for it?", verb: "lose", correctAnswer: "have lost", tense: "Present Perfect", keywordHint: "result in present" },
  { id: 111, sentenceTemplate: "The Titanic ______ ({verb}) in 1912.", verb: "sink", correctAnswer: "sank", tense: "Past Simple", keywordHint: "in 1912" },
  { id: 112, sentenceTemplate: "Listen! Someone ______ ({verb}) the piano.", verb: "play", correctAnswer: "is playing", tense: "Present Continuous", keywordHint: "Listen!" },
  { id: 113, sentenceTemplate: "If it ______ ({verb}), we will stay at home.", verb: "rain", correctAnswer: "rains", tense: "Present Simple (in conditional)", keywordHint: "If-clause type 1" },
  { id: 114, sentenceTemplate: "She ______ ({verb}) for her exams all week.", verb: "revise", correctAnswer: "has been revising", tense: "Present Perfect Continuous", keywordHint: "all week (ongoing action)" },
  { id: 115, sentenceTemplate: "He ______ ({verb}) his keys yesterday and couldn't get into his house.", verb: "forget", correctAnswer: "forgot", tense: "Past Simple", keywordHint: "yesterday" },
  { id: 116, sentenceTemplate: "This time next week, we ______ ({verb}) on a beach in Spain.", verb: "lie", correctAnswer: "will be lying", tense: "Future Continuous", keywordHint: "This time next week" },
  { id: 117, sentenceTemplate: "After he ______ ({verb}) his work, he went home.", verb: "finish", correctAnswer: "had finished", tense: "Past Perfect", keywordHint: "After (action before another past)" },
  { id: 118, sentenceTemplate: "I usually ______ ({verb}) up at 7 AM.", verb: "wake", correctAnswer: "wake", tense: "Present Simple", keywordHint: "usually" },
  { id: 119, sentenceTemplate: "Be quiet! The baby ______ ({verb}).", verb: "sleep", correctAnswer: "is sleeping", tense: "Present Continuous", keywordHint: "Be quiet! (now)" },
  { id: 120, sentenceTemplate: "They ______ ({verb}) here for three hours by the time the bus arrives.", verb: "wait", correctAnswer: "will have been waiting", tense: "Future Perfect Continuous", keywordHint: "for three hours by the time" },
  { id: 121, sentenceTemplate: "Mozart ______ ({verb}) more than 600 pieces of music.", verb: "compose", correctAnswer: "composed", tense: "Past Simple", keywordHint: "Mozart (deceased)" },
  { id: 122, sentenceTemplate: "I ______ ({verb}) to the gym later today.", verb: "go", correctAnswer: "am going", tense: "Present Continuous (future plan)", keywordHint: "later today (arranged)" },
  { id: 123, sentenceTemplate: "She ______ ({verb}) TV when I called her.", verb: "watch", correctAnswer: "was watching", tense: "Past Continuous", keywordHint: "when I called (interrupted action)" },
  { id: 124, sentenceTemplate: "We ______ ({verb}) this film before.", verb: "see", correctAnswer: "have seen", tense: "Present Perfect", keywordHint: "before (experience)" },
  { id: 125, sentenceTemplate: "The sun ______ ({verb}) in the east.", verb: "rise", correctAnswer: "rises", tense: "Present Simple", keywordHint: "general truth" },
  { id: 126, sentenceTemplate: "By 2030, scientists ______ ({verb}) a cure for that disease.", verb: "find", correctAnswer: "will have found", tense: "Future Perfect", keywordHint: "By 2030" },
  { id: 127, sentenceTemplate: "He ______ ({verb}) his leg while he was skiing.", verb: "break", correctAnswer: "broke", tense: "Past Simple", keywordHint: "while he was skiing (shorter action)" },
  { id: 128, sentenceTemplate: "It ______ ({verb}) very hard at the moment.", verb: "snow", correctAnswer: "is snowing", tense: "Present Continuous", keywordHint: "at the moment" },
  { id: 129, sentenceTemplate: "I ______ ({verb}) him for ages.", verb: "not / see", correctAnswer: "haven't seen", tense: "Present Perfect", keywordHint: "for ages" },
  { id: 130, sentenceTemplate: "The builders ______ ({verb}) the house by the end of next month.", verb: "finish", correctAnswer: "will have finished", tense: "Future Perfect", keywordHint: "by the end of next month" },
  // New 30 exercises for Mixed Tenses
  { id: 131, sentenceTemplate: "She usually ______ ({verb}) coffee in the morning, but today she ______ ({verb}) tea.", verb: "drink / have", correctAnswer: "drinks / is having", tense: "Present Simple / Present Continuous", keywordHint: "usually / today" },
  { id: 132, sentenceTemplate: "By this time next year, I ______ ({verb}) from university.", verb: "graduate", correctAnswer: "will have graduated", tense: "Future Perfect", keywordHint: "By this time next year" },
  { id: 133, sentenceTemplate: "He ______ ({verb}) when his alarm clock rang at 7 AM.", verb: "still / sleep", correctAnswer: "was still sleeping", tense: "Past Continuous", keywordHint: "when alarm rang (ongoing)" },
  { id: 134, sentenceTemplate: "If I ______ ({verb}) the lottery, I would buy a big house.", verb: "win", correctAnswer: "won", tense: "Past Simple (Conditional Type 2)", keywordHint: "If... would (unreal present)" },
  { id: 135, sentenceTemplate: "They ______ ({verb}) for the bus for an hour before it finally arrived.", verb: "wait", correctAnswer: "had been waiting", tense: "Past Perfect Continuous", keywordHint: "for an hour before it arrived" },
  { id: 136, sentenceTemplate: "What ______ you ______ ({verb}) this weekend? Any plans?", verb: "do", correctAnswer: "are you doing", tense: "Present Continuous (future plan)", keywordHint: "this weekend (plans)" },
  { id: 137, sentenceTemplate: "The Earth ______ ({verb}) around the Sun.", verb: "revolve", correctAnswer: "revolves", tense: "Present Simple", keywordHint: "general truth" },
  { id: 138, sentenceTemplate: "I ______ ({verb}) him yesterday at the park; he was walking his dog.", verb: "see", correctAnswer: "saw", tense: "Past Simple", keywordHint: "yesterday (specific event)" },
  { id: 139, sentenceTemplate: "Look out! That car ______ ({verb}) to crash!", verb: "go", correctAnswer: "is going to crash", tense: "Future (going to - imminent)", keywordHint: "Look out! (prediction based on evidence)" },
  { id: 140, sentenceTemplate: "She told me she ______ ({verb}) tired, so she went to bed early.", verb: "be", correctAnswer: "was", tense: "Past Simple (reported speech)", keywordHint: "told me (past reporting)" },
  { id: 141, sentenceTemplate: "We ______ ({verb}) this project by the end of the day.", verb: "finish", correctAnswer: "will have finished", tense: "Future Perfect", keywordHint: "by the end of the day" },
  { id: 142, sentenceTemplate: "He ______ ({verb}) to read when he was only four years old.", verb: "learn", correctAnswer: "learned", tense: "Past Simple", keywordHint: "when he was four" },
  { id: 143, sentenceTemplate: "The train ______ ({verb}) at 3:30 PM, so we should leave soon.", verb: "leave", correctAnswer: "leaves", tense: "Present Simple (timetable/schedule)", keywordHint: "at 3:30 PM (schedule)" },
  { id: 144, sentenceTemplate: "I ______ ({verb}) for my keys for the last 30 minutes, I can't find them!", verb: "look", correctAnswer: "have been looking", tense: "Present Perfect Continuous", keywordHint: "for the last 30 minutes (ongoing)" },
  { id: 145, sentenceTemplate: "While dad ______ ({verb}) the car, mom was preparing lunch.", verb: "wash", correctAnswer: "was washing", tense: "Past Continuous", keywordHint: "While (parallel past actions)" },
  { id: 146, sentenceTemplate: "If you ______ ({verb}) harder, you will pass the exam.", verb: "study", correctAnswer: "study", tense: "Present Simple (Conditional Type 1)", keywordHint: "If... will (real future)" },
  { id: 147, sentenceTemplate: "By the time she arrived, we ______ ({verb}) all the food.", verb: "eat", correctAnswer: "had eaten", tense: "Past Perfect", keywordHint: "By the time (action finished before another)" },
  { id: 148, sentenceTemplate: "My flight ______ ({verb}) at 6 AM tomorrow morning.", verb: "depart", correctAnswer: "departs", tense: "Present Simple (future schedule)", keywordHint: "tomorrow morning (fixed schedule)" },
  { id: 149, sentenceTemplate: "They ______ ({verb}) a new house next year if they save enough money.", verb: "buy", correctAnswer: "will buy", tense: "Future Simple (will - conditional)", keywordHint: "next year if (future possibility)" },
  { id: 150, sentenceTemplate: "She ______ ({verb}) very quiet today. Is everything alright?", verb: "be", correctAnswer: "is being", tense: "Present Continuous (temporary behavior)", keywordHint: "today (temporary)" },
  { id: 151, sentenceTemplate: "He ______ ({verb}) for that company since he graduated.", verb: "work", correctAnswer: "has worked", tense: "Present Perfect", keywordHint: "since he graduated (up to now)" },
  { id: 152, sentenceTemplate: "At this time tomorrow, I ______ ({verb}) on a tropical beach.", verb: "relax", correctAnswer: "will be relaxing", tense: "Future Continuous", keywordHint: "At this time tomorrow" },
  { id: 153, sentenceTemplate: "I ______ ({verb}) my old teacher while I was shopping downtown.", verb: "run into", correctAnswer: "ran into", tense: "Past Simple", keywordHint: "while I was shopping (shorter action)" },
  { id: 154, sentenceTemplate: "The children ______ ({verb}) because they had eaten too much candy.", verb: "be sick", correctAnswer: "were sick", tense: "Past Simple", keywordHint: "because they had eaten (past reason)" },
  { id: 155, sentenceTemplate: "How long ______ you ______ ({verb}) Spanish?", verb: "learn", correctAnswer: "have you been learning", tense: "Present Perfect Continuous", keywordHint: "How long (ongoing up to present)" },
  { id: 156, sentenceTemplate: "The concert ______ ({verb}) by a famous singer last night.", verb: "give", correctAnswer: "was given", tense: "Past Simple Passive", keywordHint: "by a famous singer (passive)" },
  { id: 157, sentenceTemplate: "He promised he ______ ({verb}) late for the meeting.", verb: "not / be", correctAnswer: "wouldn't be", tense: "Future in the Past", keywordHint: "promised" },
  { id: 158, sentenceTemplate: "This time last year, we ______ ({verb}) through Europe.", verb: "travel", correctAnswer: "were travelling", tense: "Past Continuous", keywordHint: "This time last year (ongoing)" },
  { id: 159, sentenceTemplate: "If she ______ ({verb}) about the party, she would have come.", verb: "know", correctAnswer: "had known", tense: "Past Perfect (Conditional Type 3)", keywordHint: "If... would have (unreal past)" },
  { id: 160, sentenceTemplate: "The package ______ ({verb}) tomorrow morning.", verb: "deliver", correctAnswer: "will be delivered", tense: "Future Simple Passive", keywordHint: "tomorrow morning (passive)" },
];

export const PAST_SIMPLE_PAST_CONTINUOUS_EXERCISES: Exercise[] = [
  // Past Simple vs Past Continuous (Existing 30)
  { id: 201, sentenceTemplate: "While I ______ ({verb}) my homework, my brother was playing video games.", verb: "do", correctAnswer: "was doing", tense: "Past Continuous", keywordHint: "While (parallel ongoing)" },
  { id: 202, sentenceTemplate: "She ______ ({verb}) a delicious cake for the party yesterday.", verb: "bake", correctAnswer: "baked", tense: "Past Simple", keywordHint: "yesterday (completed)" },
  { id: 203, sentenceTemplate: "The sun ______ ({verb}) when I woke up this morning.", verb: "shine", correctAnswer: "was shining", tense: "Past Continuous", keywordHint: "when I woke up (background)" },
  { id: 204, sentenceTemplate: "He ______ ({verb}) his keys, so he couldn't open the door.", verb: "lose", correctAnswer: "lost", tense: "Past Simple", keywordHint: "so he couldn't (completed result)" },
  { id: 205, sentenceTemplate: "They ______ ({verb}) football in the park when it started to rain.", verb: "play", correctAnswer: "were playing", tense: "Past Continuous", keywordHint: "when it started (interrupted)" },
  { id: 206, sentenceTemplate: "I ______ ({verb}) him at the library last Monday.", verb: "see", correctAnswer: "saw", tense: "Past Simple", keywordHint: "last Monday (specific event)" },
  { id: 207, sentenceTemplate: "What ______ you ______ ({verb}) at 10 p.m. last night?", verb: "do", correctAnswer: "were doing", tense: "Past Continuous", keywordHint: "at 10 p.m. (specific time ongoing)" },
  { id: 208, sentenceTemplate: "The bird ______ ({verb}) beautifully while we were having breakfast.", verb: "sing", correctAnswer: "was singing", tense: "Past Continuous", keywordHint: "while (parallel ongoing)" },
  { id: 209, sentenceTemplate: "He ______ ({verb}) the window and looked outside.", verb: "open", correctAnswer: "opened", tense: "Past Simple", keywordHint: "and (sequence of actions)" },
  { id: 210, sentenceTemplate: "It ______ ({verb}) heavily when I left the house.", verb: "rain", correctAnswer: "was raining", tense: "Past Continuous", keywordHint: "when I left (background)" },
  { id: 211, sentenceTemplate: "She ______ ({verb}) her ankle while she was jogging.", verb: "twist", correctAnswer: "twisted", tense: "Past Simple", keywordHint: "while (shorter action interrupting)" },
  { id: 212, sentenceTemplate: "The children ______ ({verb}) a sandcastle when the wave came.", verb: "build", correctAnswer: "were building", tense: "Past Continuous", keywordHint: "when the wave came (interrupted)" },
  { id: 213, sentenceTemplate: "He ______ ({verb}) for the bus when he saw his friend.", verb: "wait", correctAnswer: "was waiting", tense: "Past Continuous", keywordHint: "when he saw (background)" },
  { id: 214, sentenceTemplate: "I ______ ({verb}) a book when the lights suddenly went out.", verb: "read", correctAnswer: "was reading", tense: "Past Continuous", keywordHint: "when... went out (interrupted)" },
  { id: 215, sentenceTemplate: "They ______ ({verb}) to music, so they didn't hear the doorbell.", verb: "listen", correctAnswer: "were listening", tense: "Past Continuous", keywordHint: "so they didn't hear (reason)" },
  { id: 216, sentenceTemplate: "He ______ ({verb}) his dinner quickly and rushed out.", verb: "eat", correctAnswer: "ate", tense: "Past Simple", keywordHint: "and rushed out (sequence)" },
  { id: 217, sentenceTemplate: "While my mom ______ ({verb}), my dad was washing the car.", verb: "cook", correctAnswer: "was cooking", tense: "Past Continuous", keywordHint: "While (parallel ongoing)" },
  { id: 218, sentenceTemplate: "The phone ______ ({verb}) while I was taking a shower.", verb: "ring", correctAnswer: "rang", tense: "Past Simple", keywordHint: "while (shorter action interrupting)" },
  { id: 219, sentenceTemplate: "We ______ ({verb}) in the garden when we heard a loud noise.", verb: "sit", correctAnswer: "were sitting", tense: "Past Continuous", keywordHint: "when we heard (background)" },
  { id: 220, sentenceTemplate: "She ______ ({verb}) TV all evening yesterday.", verb: "watch", correctAnswer: "watched", tense: "Past Simple", keywordHint: "all evening yesterday (completed duration)" },
  { id: 221, sentenceTemplate: "As I ______ ({verb}) down the street, I saw an old friend.", verb: "walk", correctAnswer: "was walking", tense: "Past Continuous", keywordHint: "As I... (background)" },
  { id: 222, sentenceTemplate: "He ______ ({verb}) when the teacher asked him a question.", verb: "not / pay attention", correctAnswer: "wasn't paying attention", tense: "Past Continuous", keywordHint: "when the teacher asked" },
  { id: 223, sentenceTemplate: "The cat ______ ({verb}) on the sofa while I was working.", verb: "sleep", correctAnswer: "was sleeping", tense: "Past Continuous", keywordHint: "while I was working" },
  { id: 224, sentenceTemplate: "She ______ ({verb}) a letter to her friend last night.", verb: "write", correctAnswer: "wrote", tense: "Past Simple", keywordHint: "last night (completed)" },
  { id: 225, sentenceTemplate: "When I entered the room, everyone ______ ({verb}).", verb: "talk", correctAnswer: "was talking", tense: "Past Continuous", keywordHint: "When I entered (ongoing scene)" },
  { id: 226, sentenceTemplate: "He ______ ({verb}) his car when the accident happened.", verb: "drive", correctAnswer: "was driving", tense: "Past Continuous", keywordHint: "when the accident happened" },
  { id: 227, sentenceTemplate: "I ______ ({verb}) my homework, then I went to bed.", verb: "finish", correctAnswer: "finished", tense: "Past Simple", keywordHint: "then (sequence)" },
  { id: 228, sentenceTemplate: "The students ______ ({verb}) a test when the fire alarm went off.", verb: "take", correctAnswer: "were taking", tense: "Past Continuous", keywordHint: "when the fire alarm went off" },
  { id: 229, sentenceTemplate: "It ______ ({verb}) dark when we left the cinema.", verb: "get", correctAnswer: "was getting", tense: "Past Continuous", keywordHint: "when we left (process)" },
  { id: 230, sentenceTemplate: "She ______ ({verb}) her coffee when she suddenly felt ill.", verb: "drink", correctAnswer: "was drinking", tense: "Past Continuous", keywordHint: "when she suddenly felt (interrupted)" },
  // New 30 exercises for Past Simple vs Past Continuous
  { id: 231, sentenceTemplate: "The lights ______ ({verb}) out while I was reading.", verb: "go", correctAnswer: "went", tense: "Past Simple", keywordHint: "while (shorter interrupting action)" },
  { id: 232, sentenceTemplate: "He ______ ({verb}) on his phone when the teacher called his name.", verb: "look", correctAnswer: "was looking", tense: "Past Continuous", keywordHint: "when (ongoing action interrupted)" },
  { id: 233, sentenceTemplate: "She ______ ({verb}) her keys and couldn't get into the car.", verb: "drop", correctAnswer: "dropped", tense: "Past Simple", keywordHint: "and (sequence of events)" },
  { id: 234, sentenceTemplate: "It ______ ({verb}) heavily when we decided to go for a walk.", verb: "snow", correctAnswer: "was snowing", tense: "Past Continuous", keywordHint: "when we decided (background state)" },
  { id: 235, sentenceTemplate: "I ______ ({verb}) dinner when my friend arrived unexpectedly.", verb: "prepare", correctAnswer: "was preparing", tense: "Past Continuous", keywordHint: "when (ongoing action interrupted)" },
  { id: 236, sentenceTemplate: "They ______ ({verb}) a movie last night at the cinema.", verb: "watch", correctAnswer: "watched", tense: "Past Simple", keywordHint: "last night (completed action)" },
  { id: 237, sentenceTemplate: "While the children ______ ({verb}) in the garden, their mother was reading a book.", verb: "play", correctAnswer: "were playing", tense: "Past Continuous", keywordHint: "While (parallel ongoing actions)" },
  { id: 238, sentenceTemplate: "He ______ ({verb}) off the ladder while he was painting the ceiling.", verb: "fall", correctAnswer: "fell", tense: "Past Simple", keywordHint: "while (shorter action during longer one)" },
  { id: 239, sentenceTemplate: "The band ______ ({verb}) their most popular song when the power went out.", verb: "perform", correctAnswer: "was performing", tense: "Past Continuous", keywordHint: "when (ongoing action interrupted)" },
  { id: 240, sentenceTemplate: "I ______ ({verb}) my homework, then I watched TV.", verb: "do", correctAnswer: "did", tense: "Past Simple", keywordHint: "then (sequence of completed actions)" },
  { id: 241, sentenceTemplate: "What ______ you ______ ({verb}) when you heard the strange noise?", verb: "do", correctAnswer: "were you doing", tense: "Past Continuous", keywordHint: "when you heard (ongoing action at time of event)" },
  { id: 242, sentenceTemplate: "She ______ ({verb}) very fast when she had the accident.", verb: "drive", correctAnswer: "was driving", tense: "Past Continuous", keywordHint: "when (ongoing action at time of event)" },
  { id: 243, sentenceTemplate: "He ______ ({verb}) the book and put it back on the shelf.", verb: "close", correctAnswer: "closed", tense: "Past Simple", keywordHint: "and (sequence)" },
  { id: 244, sentenceTemplate: "The birds ______ ({verb}) when I woke up this morning.", verb: "sing", correctAnswer: "were singing", tense: "Past Continuous", keywordHint: "when I woke up (background)" },
  { id: 245, sentenceTemplate: "While I ______ ({verb}) for the bus, I saw an old classmate.", verb: "wait", correctAnswer: "was waiting", tense: "Past Continuous", keywordHint: "While (longer action interrupted)" },
  { id: 246, sentenceTemplate: "He ______ ({verb}) tired, so he went to bed early.", verb: "feel", correctAnswer: "felt", tense: "Past Simple", keywordHint: "so (reason for subsequent action)" },
  { id: 247, sentenceTemplate: "They ______ ({verb}) about their holiday plans when I joined them.", verb: "talk", correctAnswer: "were talking", tense: "Past Continuous", keywordHint: "when I joined (ongoing discussion)" },
  { id: 248, sentenceTemplate: "I ______ ({verb}) my phone while I was getting off the bus.", verb: "drop", correctAnswer: "dropped", tense: "Past Simple", keywordHint: "while (shorter action during longer one)" },
  { id: 249, sentenceTemplate: "The chef ______ ({verb}) a new dish when the manager entered the kitchen.", verb: "create", correctAnswer: "was creating", tense: "Past Continuous", keywordHint: "when (ongoing action interrupted)" },
  { id: 250, sentenceTemplate: "We ______ ({verb}) a lovely picnic in the park yesterday.", verb: "have", correctAnswer: "had", tense: "Past Simple", keywordHint: "yesterday (completed event)" },
  { id: 251, sentenceTemplate: "She ______ ({verb}) a beautiful dress to the party.", verb: "wear", correctAnswer: "wore", tense: "Past Simple", keywordHint: "to the party (completed action)" },
  { id: 252, sentenceTemplate: "While Tom ______ ({verb}) a book, his sister was listening to music.", verb: "read", correctAnswer: "was reading", tense: "Past Continuous", keywordHint: "While (parallel actions)" },
  { id: 253, sentenceTemplate: "The dog ______ ({verb}) loudly when the postman arrived.", verb: "bark", correctAnswer: "was barking", tense: "Past Continuous", keywordHint: "when (ongoing action at time of event)" },
  { id: 254, sentenceTemplate: "He ______ ({verb}) his leg while he was playing football.", verb: "break", correctAnswer: "broke", tense: "Past Simple", keywordHint: "while (shorter action interrupting)" },
  { id: 255, sentenceTemplate: "It ______ ({verb}) when we left the cinema.", verb: "not / rain", correctAnswer: "wasn't raining", tense: "Past Continuous", keywordHint: "when we left (state at that time)" },
  { id: 256, sentenceTemplate: "I ______ ({verb}) to my friend on the phone when my battery died.", verb: "talk", correctAnswer: "was talking", tense: "Past Continuous", keywordHint: "when (ongoing action interrupted)" },
  { id: 257, sentenceTemplate: "They ______ ({verb}) the match, so they were very happy.", verb: "win", correctAnswer: "won", tense: "Past Simple", keywordHint: "so (reason for happiness)" },
  { id: 258, sentenceTemplate: "The sun ______ ({verb}) brightly and the birds were singing.", verb: "shine", correctAnswer: "was shining", tense: "Past Continuous", keywordHint: "and (parallel background states)" },
  { id: 259, sentenceTemplate: "She ______ ({verb}) her coffee and then left for work.", verb: "finish", correctAnswer: "finished", tense: "Past Simple", keywordHint: "and then (sequence)" },
  { id: 260, sentenceTemplate: "While we ______ ({verb}) dinner, we discussed our plans for the weekend.", verb: "have", correctAnswer: "were having", tense: "Past Continuous", keywordHint: "While (during the activity)" },
];

export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash-preview-04-17';
